# Generated by Django 4.2.6 on 2023-12-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_nbpersonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='nbPersonne',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=2),
        ),
    ]
