# Generated by Django 4.2.6 on 2023-12-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['name'], 'verbose_name': 'Menu'},
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('drinks', 'drinks'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=50, null=True),
        ),
    ]
